### ISSUE TITLE
Panic when creating AWS privatelink endpoint

### ISSUE THREAD

**Issue by MuriukiPM** [mongodb/terraform-provider-mongodbatlas#1067]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```sh
$ terraform version
Terraform v1.3.4
on darwin_arm64
```
```hcl
terraform {
  required_version = ">= 1.2.0"
  required_providers {
    mongodbatlas = {
      source = "mongodb/mongodbatlas"
      version = "1.8.0"
    }
  }
}
```

### Terraform Configuration File 

Using MONGODB_ATLAS_PUBLIC_KEY and MONGODB_ATLAS_PRIVATE_KEY environment variables
```hcl
provider "mongodbatlas" {}
```
Configuration for the resource
```hcl
resource "mongodbatlas_privatelink_endpoint" "test" {
  project_id    = var.mongodb_atlas["project_id"]
  provider_name = "AWS"
  region        = "US_EAST_1"

  timeouts {
    create = "30m"
    delete = "20m"
  }
}
```
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Expected Behavior

A private endpoint should have been created. 

### Crash Output

```
mongodbatlas_privatelink_endpoint.test: Creating...
mongodbatlas_privatelink_endpoint.test: Still creating... [10s elapsed]
╷
│ Error: Request cancelled
│ 
│   with mongodbatlas_privatelink_endpoint.test,
│   on mongodbatlas.tf line 52, in resource "mongodbatlas_privatelink_endpoint" "test":
│   52: resource "mongodbatlas_privatelink_endpoint" "test" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-mongodbatlas_v1.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104a260b4]

goroutine 74 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourcePrivateLinkEndpointRefreshFunc.func1()
        github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_privatelink_endpoint.go:309 +0x54
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1()
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:110 +0x174
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/resource/state.go:83 +0x1a8

Error: The terraform-provider-mongodbatlas_v1.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


Begin cleanup...
Done.
```

### Additional Context

On the atlas dashboard, I could see the Endpoint was created. I terminated and retried to apply the configuration a second time which worked.

**Comment by martinstibbe** [comment]
@MuriukiPM I was able to apply your example it worked after ~2m

mongodbatlas_privatelink_endpoint.test: Creation complete after 2m52s 
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

**Comment by MuriukiPM** [comment]
> @MuriukiPM I was able to apply your example it worked after ~2m
> 
> mongodbatlas_privatelink_endpoint.test: Creation complete after 2m52s Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

@martinstibbe the panic happened once for me, on retry it applied successfully. I wasn't sure what could have caused the panic hence the posted issue but I understand it may not be reproducible.

**Comment by Zuhairahmed** [comment]
Thanks @MuriukiPM, closing this issue but feel free to re-open if this comes up again.
