### ISSUE TITLE
The terraform-provider-mongodbatlas_v1.12.2 plugin crashed!

### ISSUE THREAD

**Issue by hanyouqing** [mongodb/terraform-provider-mongodbatlas#1567]
> This issue can be fixed by downgrading the provider version to 1.12.0

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```bash
$ terraform version
Terraform v1.6.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.22.0
+ provider registry.terraform.io/hashicorp/vault v3.21.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.12.2
```

### Terraform Configuration File 

```hcl
# Copy-paste all your configuration (e.g. main.tf and variable.tf) info here
```

### Steps to Reproduce

Please be **as detailed as possible.**
* If the issue **involves version changes** (e.g. `run plan with version 1.k.x then re-run with version 1.k.y`), please make sure you report the detailed sequence on commands to execute.
* If the issue requires **changes from the UI**, please document them **preferably with screenshots**.

```hcl
# Write here the detailed list of required steps.
```

### Crash Output

```bash


│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ReadResource request was cancelled.
╵
Releasing state lock. This may take a few moments...
Stack trace from the terraform-provider-mongodbatlas_v1.12.2 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105bd37d0]
goroutine 14 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.(*ProjectRS).Read(0x14000153458, {0x1064a4c70, 0x14000ba55c0}, {{{{0x1064ab570, 0x140008cd950}, {0x106267700, 0x14000a77da0}}, {0x1064ad9a0, 0x140001582d0}}, 0x1400017e038, ...}, ...)
	github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/fw_resource_mongodbatlas_project.go:403 +0x290
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x140000c6000, {0x1064a4c70, 0x14000ba55c0}, 0x14000ba5650, 0x14000429580)
	github.com/hashicorp/terraform-plugin-framework@v1.4.1/internal/fwserver/server_readresource.go:101 +0x508
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x140000c6000, {0x1064a4c70?, 0x14000ba5470?}, 0x14000146dc0)
	github.com/hashicorp/terraform-plugin-framework@v1.4.1/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x1064a4bc8?, {0x1064a4c70?, 0x14000ba5140?}, 0x14000146dc0)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ReadResource.go:35 +0x188
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400028c0a0, {0x1064a4c70?, 0x14000ba4780?}, 0x14000154840)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:787 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1064271e0?, 0x1400028c0a0}, {0x1064a4c70, 0x14000ba4780}, 0x140000c43f0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:431 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000410000, {0x1064abd40, 0x140007029c0}, 0x14000ba3d40, 0x1400040e960, 0x106f7f0e8, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000410000, {0x1064abd40, 0x140007029c0}, 0x14000ba3d40, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c
Error: The terraform-provider-mongodbatlas_v1.12.2 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
[ERROR] Error while trying to get terraform plan
```

**Comment by AgustinBettati** [comment]
Hello @hanyouqing.

Taking into account our ["One-click reproducible issues" principle](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md#one-click-reproducible-issues-principle) defined in our guidelines, could you help us by providing the terraform configuration and terraform commands used to reach this plugin crash?
