### ISSUE TITLE
[Bug]: Unable to create billing alert configuration.

### ISSUE THREAD

**Issue by yaboeing** [mongodb/terraform-provider-mongodbatlas#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.15.1

### Terraform Version

v1.5.7

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

I've tried to create `mongodbatlas_alert_configuration` with `event_type = "DAILY_BILL_OVER_THRESHOLD"` but have got an error on apply

```
│ Error: Missing required argument
│ 
│   on alert_configurations.tf line 264, in resource "mongodbatlas_alert_configuration" "pending_invoice_over_threshold":
│  264:   metric_threshold_config {
│ 
│ The argument "metric_name" is required, but no definition was found.

```

I've tried to import the same UI-created-recourse but it doesn't work either, cause I got an error with the following stack trace

<details closed>
  <summary>import stack trace</summary>

```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-mongodbatlas_v1.15.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x103251764]

goroutine 45 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/internal/service/alertconfiguration.NewTFThresholdConfigModel(0x14000c696e0, {0x0?, 0x0?, 0x0?})
        github.com/mongodb/terraform-provider-mongodbatlas/internal/service/alertconfiguration/model_alert_configuration.go:237 +0x64
github.com/mongodb/terraform-provider-mongodbatlas/internal/service/alertconfiguration.NewTFAlertConfigurationModel(_, _)
        github.com/mongodb/terraform-provider-mongodbatlas/internal/service/alertconfiguration/model_alert_configuration.go:107 +0x1e8
github.com/mongodb/terraform-provider-mongodbatlas/internal/service/alertconfiguration.(*alertConfigurationRS).Read(0x14000939020?, {0x103da4fb8, 0x14000939020}, {{{{0x103dab6f0, 0x14000984330}, {0x103ab80a0, 0x140009840f0}}, {0x103daf000, 0x14000b10910}}, 0x14000076968, ...}, ...)
        github.com/mongodb/terraform-provider-mongodbatlas/internal/service/alertconfiguration/resource_alert_configuration.go:437 +0x328
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x1400009a9c0, {0x103da4fb8, 0x14000939020}, 0x140009390e0, 0x140009d5600)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_readresource.go:101 +0x514
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x1400009a9c0, {0x103da4fb8?, 0x14000938f00?}, 0x140008bc400)
        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_readresource.go:55 +0x314
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x103da4ff0?, {0x103da4fb8?, 0x14000938c00?}, 0x140008bc400)
        github.com/hashicorp/terraform-plugin-mux@v0.14.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140005f8aa0, {0x103da4fb8?, 0x140009381e0?}, 0x140008ca0c0)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/tf6server/server.go:775 +0x3c4
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x103d0fd20?, 0x140005f8aa0}, {0x103da4fb8, 0x140009381e0}, 0x140008d6000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000175400, {0x103da4fb8, 0x14000938150}, {0x103dac848, 0x140006029c0}, 0x140009b8000, 0x1400054d320, 0x104b991c8, 0x0)
        google.golang.org/grpc@v1.61.0/server.go:1385 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x14000175400, {0x103dac848, 0x140006029c0}, 0x140009b8000)
        google.golang.org/grpc@v1.61.0/server.go:1796 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.0/server.go:1029 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
        google.golang.org/grpc@v1.61.0/server.go:1040 +0x150

Error: The terraform-provider-mongodbatlas_v1.15.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.



````
</details>

As a reference, I've used [API spec](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Alert-Configurations/operation/createAlertConfiguration) and the response from the API endpoint `https://cloud.mongodb.com/api/atlas/v2/groups/org_id/alertConfigs`, but I can't find `metric_name` there.

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_alert_configuration" "pending_invoice_over_threshold" {
  enabled    = true
  project_id = "project_name"
  event_type = "PENDING_INVOICE_OVER_THRESHOLD"

  metric_threshold_config {
    operator  = "GREATER_THAN"
    threshold = 100
  }

  notification {
    delay_min     = 0
    email_enabled = true
    interval_min  = 60
    roles = [
      "GROUP_OWNER",
    ]
    sms_enabled = false
    type_name   = "GROUP"
  }

}
```

### Steps To Reproduce

1) Prepare resource definition
2) Apply

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oarbusi** [comment]
Hi @yaboeing thanks for the details provided,
As per the documentation, [metric_threshold_config](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/alert_configuration#metric-threshold-config-metric_threshold_config) requires `metric_name`. `metric_threshold_config` is only required if `event_type` is  `OUTSIDE_METRIC_THRESHOLD` or `OUTSIDE_SERVERLESS_METRIC_THRESHOLD`, which is not your case.
As per my understanding, you should use [threshold_config](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/alert_configuration#threshold-config-threshold_config) block instead.
Please let us know if using `threshold_config` the issue is solved

**Comment by yaboeing** [comment]
Hello, @oarbusi that is a nice explanation, many thanks for that, it works like a charm. Sorry for bothering you.
