### ISSUE TITLE
Error when create or import cluster - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by afonsoaugusto** [mongodb/terraform-provider-mongodbatlas#243]
Terraform version: 0.12.26  
Go runtime version: go1.12.13
found provider "terraform-provider-mongodbatlas_v0.6.0_x4"

```

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe0a598]
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: 
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: goroutine 41 [running]:
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas.flattenProcessArgs(...)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cluster.go:1176
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasClusterRead(0xc0002a8850, 0xfbd740, 0xc0004f4a00, 0xc0002a8850, 0x0)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cluster.go:732 +0x2f38
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000f4480, 0xc00008cf50, 0xfbd740, 0xc0004f4a00, 0xc00028ce10, 0x0, 0x0)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x119
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0006da0d8, 0x135b560, 0xc000369a70, 0xc0006c2600, 0xc0006da0d8, 0xc000369a70, 0xc00054cb88)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1068e00, 0xc0006da0d8, 0x135b560, 0xc000369a70, 0xc0006c25a0, 0x0, 0x135b560, 0xc000369a70, 0xc0008c2480, 0x41d)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003f01a0, 0x1366a00, 0xc000202a80, 0xc000192300, 0xc000180f60, 0x1ac0eb0, 0x0, 0x0, 0x0)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:1082 +0x50a
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0003f01a0, 0x1366a00, 0xc000202a80, 0xc000192300, 0x0)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:1405 +0xcc9
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002801d0, 0xc0003f01a0, 0x1366a00, 0xc000202a80, 0xc000192300)
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:746 +0xa1
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-06-13T22:19:49.509-0300 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.0_x4:  /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:744 +0xa1
2020/06/13 22:19:49 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/06/13 22:19:49 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020-06-13T22:19:49.514-0300 [DEBUG] plugin: plugin process exited: path=/home/afonsorodrigues/projetos/meus-projetos/mongodb-terraform-example/.terraform/plugins/linux_amd64/terraform-provider-mongodbatlas_v0.6.0_x4 pid=19739 error="exit status 2"
2020/06/13 22:19:49 [TRACE] [walkImport] Exiting eval tree: import mongodbatlas_cluster.cluster_example result
2020/06/13 22:19:49 [TRACE] vertex "import mongodbatlas_cluster.cluster_example result": visit complete
2020/06/13 22:19:49 [TRACE] vertex "mongodbatlas_cluster.cluster_example (import id \"5ee571492eb6b363bdb4fe9b-clusterterraform\")": dynamic subgraph encountered errors
2020/06/13 22:19:49 [TRACE] vertex "mongodbatlas_cluster.cluster_example (import id \"5ee571492eb6b363bdb4fe9b-clusterterraform\")": visit complete
2020/06/13 22:19:49 [TRACE] dag/walk: upstream of "provider.mongodbatlas (close)" errored, so skipping
2020/06/13 22:19:49 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/06/13 22:19:49 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/06/13 22:19:49 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-06-13T22:19:49.515-0300 [DEBUG] plugin: plugin exited
```

When change version from "v0.6.0" to "v0.5.1", I created the cluster.

**Comment by themantissa** [comment]
@afonsoaugusto  thank you for the issue report.  We'll investigate and report our findings as soon as possible.

**Comment by PacoDw** [comment]
Hello, @afonsoaugusto thank you so much for your review, I added the code to fix this issue so could you test the branch `fix-#243` to check if your issue persists?

Let me know if you have a comment or concern, thanks :)

**Comment by themantissa** [comment]
@afonsoaugusto wanted to check in and see if this fix has corrected the issue?

**Comment by afonsoaugusto** [comment]
Thanks @PacoDw and @themantissa,
I will check de fix and report.

**Comment by themantissa** [comment]
Hi @afonsoaugusto if you have any more issues please let u sknow.  This is closed as 0.6.1 w/ the fix is built and should be released by HashiCorp officially soon.

**Comment by afonsoaugusto** [comment]
Thanks @themantissa, I'll migrate the provider to 0.6.1 as soon its is disponible.
Thank's for your answer and review.

**Comment by WafflesMcDuff** [comment]
Please reopen

**Comment by WafflesMcDuff** [comment]
This issue is still occuring in 0.6.1
```
mongodbatlas_database_user.admin: Modifying... [id=cHJvamVjdF9pZA==:NWUyMGUyNjljNTZjOTgyM2VhNzRiOTAx-dXNlcm5hbWU=:dGVzdC0yMDYwMzAtY2FsbC1tZXRob2Qtc3ZjLWFkbWlu-YXV0aF9kYXRhYmFzZV9uYW1l:YWRtaW4=]
mongodbatlas_cluster.main: Modifying... [id=Y2x1c3Rlcl9pZA==:NWUyYTFhYjNmMmEzMGI1NjZhZTAyYzUz-cHJvamVjdF9pZA==:NWUyMGUyNjljNTZjOTgyM2VhNzRiOTAx-Y2x1c3Rlcl9uYW1l:dGVzdC0yMDYwMzAtY2FsbC1tZXRob2Qtc3Zj]

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe0ca94]
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: goroutine 42 [running]:
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasClusterUpdate(0xc0001c21c0, 0xfbd740, 0xc0001b7400, 0x24, 0x1afc460)
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cluster.go:791 +0x1c64
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000113950, 0xc00043e5f0, 0xc00023a780, 0xfbd740, 0xc0001b7400, 0xf4bc01, 0xc0006758a0, 0xc0001119b0)
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:316 +0x263
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000102080, 0xc000675a20, 0xc00043e5f0, 0xc00023a780, 0xc00010ace8, 0xc00000e530, 0xf4d960)
2020-06-29T17:42:00.384Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00009e868, 0x135b640, 0xc0003e0fc0, 0xc000248000, 0xc00009e868, 0xc0003e0fc0, 0xc000544b88)
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1068e00, 0xc00009e868, 0x135b640, 0xc0003e0fc0, 0xc0000a0f00, 0x0, 0x135b640, 0xc0003e0fc0, 0xc000662000, 0x1d7d)
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a6000, 0x1366ae0, 0xc000001b00, 0xc0000f8600, 0xc000146c60, 0x1ac1ee0, 0x0, 0x0, 0x0)
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:1082 +0x50a
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000a6000, 0x1366ae0, 0xc000001b00, 0xc0000f8600, 0x0)
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:1405 +0xcc9
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036220, 0xc0000a6000, 0x1366ae0, 0xc000001b00, 0xc0000f8600)
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:746 +0xa1
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-06-29T17:42:00.385Z [DEBUG] plugin.terraform-provider-mongodbatlas_v0.6.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/vendor/google.golang.org/grpc/server.go:744 +0xa1
2020-06-29T17:42:00.386Z [DEBUG] plugin: plugin process exited: path=/build/562782570169/global/test/mongodbatlas-cluster/.terragrunt-cache/Z69C3qz8i-NffRkNNdKvxOqfLes/jXFi4kSNbAoWvcOELYluHMN31w8/modules/mongodbatlas-cluster/.terraform/plugins/linux_amd64/terraform-provider-mongodbatlas_v0.6.1_x4 pid=285 error="exit status 2"
2020/06/29 17:42:00 [DEBUG] mongodbatlas_database_user.admin: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/06/29 17:42:00 [TRACE] EvalWriteState: recording 0 dependencies for mongodbatlas_database_user.admin
2020/06/29 17:42:00 [TRACE] EvalWriteState: writing current state object for mongodbatlas_database_user.admin
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/06/29 17:42:00 [TRACE] EvalApplyProvisioners: mongodbatlas_database_user.admin is not freshly-created, so no provisioning is required
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/06/29 17:42:00 [TRACE] EvalWriteState: recording 0 dependencies for mongodbatlas_database_user.admin
2020/06/29 17:42:00 [TRACE] EvalWriteState: writing current state object for mongodbatlas_database_user.admin
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalIf
2020/06/29 17:42:00 [DEBUG] mongodbatlas_cluster.main: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/06/29 17:42:00 [TRACE] EvalWriteState: recording 0 dependencies for mongodbatlas_cluster.main
2020/06/29 17:42:00 [TRACE] EvalWriteState: writing current state object for mongodbatlas_cluster.main
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalIf
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/06/29 17:42:00 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/06/29 17:42:00 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/06/29 17:42:00 [TRACE] [walkApply] Exiting eval tree: mongodbatlas_database_user.admin
2020/06/29 17:42:00 [TRACE] vertex "mongodbatlas_database_user.admin": visit complete
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/06/29 17:42:00 [TRACE] EvalApplyProvisioners: mongodbatlas_cluster.main is not freshly-created, so no provisioning is required
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/06/29 17:42:00 [TRACE] EvalWriteState: recording 0 dependencies for mongodbatlas_cluster.main
2020/06/29 17:42:00 [TRACE] EvalWriteState: writing current state object for mongodbatlas_cluster.main
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalIf
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalIf
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/06/29 17:42:00 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/06/29 17:42:00 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/06/29 17:42:00 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/06/29 17:42:00 [TRACE] [walkApply] Exiting eval tree: mongodbatlas_cluster.main
2020/06/29 17:42:00 [TRACE] vertex "mongodbatlas_cluster.main": visit complete
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.mongo_uri_with_options" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.mongo_db_version" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "provider.mongodbatlas (close)" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.mongo_uri_updated" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.cluster_id" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.state_name" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.mongo_uri" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.srv_address" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "output.paused" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/06/29 17:42:00 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/06/29 17:42:00 [DEBUG] POST https://hal.zone/api/integrations/terraform/3270/state/562782570169.global.test.mongodbatlas-cluster?ID=57ce6e81-0867-0ef5-b37f-f00279d07549
2020/06/29 17:42:00 [DEBUG] UNLOCK https://hal.zone/api/integrations/terraform/3270/state/562782570169.global.test.mongodbatlas-cluster
2020-06-29T17:42:00.567Z [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
[terragrunt] 2020/06/29 17:42:00 Detected 1 Hooks
[terragrunt] 2020/06/29 17:42:00 Hit multiple errors:
exit status 1
```

**Comment by themantissa** [comment]
@WafflesMcDuff can you include your terraform config and full DEBUG logs?  If you don't want to include here you can reach out directly to melissa.plunkett@mongodb.com.

**Comment by WafflesMcDuff** [comment]
Just to keep everyone on the same page, @themantissa  and I are communicating via email so I can send complete crash logs and such while limiting distribution of detailed logs

**Comment by themantissa** [comment]
@WafflesMcDuff thanks to your data @PacoDw has narrowed it down.  It's similar to this issue but is a different nil pointer issue.  He's working on the fix and testing it by FYI for you and others.

**Comment by PacoDw** [comment]
Hello @WafflesMcDuff, thank you so much for sharing your log files with us, they really helped us find the issue. I created a PR with the fix, also I tested with your TF configuration and all it's okay,  so could you test with that branch to check if now it's okay?

Let us know if you have another comment or concern 👍

**Comment by WafflesMcDuff** [comment]
Hi @PacoDw -
I feel like I’ve spent half my morning trying to get all the dependencies needed to run make tools on this PR, but I feel like I’m no closer to being done. The last error I got was:

```
root@HMX2TQ2:~/development/terraform-providers/terraform-provider-mongodbatlas# make tools
GO111MODULE=on go install github.com/client9/misspell/cmd/misspell
GO111MODULE=on go install github.com/golangci/golangci-lint/cmd/golangci-lint
# github.com/golangci/golangci-lint/internal/cache
/root/go/src/github.com/golangci/golangci-lint/internal/cache/default.go:78:15: undefined: os.UserCacheDir
# github.com/quasilyte/go-ruleguard/ruleguard/typematch
/root/go/src/github.com/quasilyte/go-ruleguard/ruleguard/typematch/typematch.go:74:15: undefined: strings.ReplaceAll
/root/go/src/github.com/quasilyte/go-ruleguard/ruleguard/typematch/typematch.go:114:14: undefined: types.NewInterfaceType
# github.com/securego/gosec/rules
/root/go/src/github.com/securego/gosec/rules/tls.go:124:7: undefined: tls.VersionTLS13
# honnef.co/go/tools/go/ir
/root/go/src/honnef.co/go/tools/go/ir/builder.go:55:16: undefined: types.NewInterfaceType
# honnef.co/go/tools/config
/root/go/src/honnef.co/go/tools/config/config.go:26:16: undefined: os.UserCacheDir
GNUmakefile:35: recipe for target 'tools' failed
make: *** [tools] Error 2
```

**Comment by WafflesMcDuff** [comment]
@PacoDw  - Ignore my last message. Upgrading go to version 1.14 fixed the errors, it seems.

**Comment by WafflesMcDuff** [comment]
@PacoDw  - This fixed the issue I was experiencing

**Comment by WafflesMcDuff** [comment]
@PacoDw - Now that we know this fixes the bug, how long before we see a new release of the provider?

**Comment by themantissa** [comment]
@WafflesMcDuff we normally release (just about) every month to get what we have out there quickly but since we have a few bug fixes ready we'll likely try to get out a small release fairly soon, i.e. 0.6.2.
