### ISSUE TITLE
Plugin crash when changing value of iam_assumed_role_arn for resource mongodbatlas_cloud_provider_access_authorization

### ISSUE THREAD

**Issue by gdelbergue** [mongodb/terraform-provider-mongodbatlas#565]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
terraform version: 1.0.7
MongoDB Atlas Provider version: 1.0.1
```

### Terraform Configuration File 

```hcl
resource "aws_kms_key" "aws_kms_key_mongodb_atlas" {
  description             = "KMS key for MongoDB Atlas ${var.project_name} cluster"
  deletion_window_in_days = 10
  enable_key_rotation     = true
}

resource "aws_iam_role" "mongodb_atlas_setup_role" {
  name = "mongodb_atlas_setup_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = ["sts:AssumeRole"]
        Effect = "Allow"
        Principal: {
          "AWS": "${mongodbatlas_cloud_provider_access_setup.mongodb_atlas_setup_only.aws.atlas_aws_account_arn}"
        },
        Condition: {
          StringEquals: {
            "sts:ExternalId": "${mongodbatlas_cloud_provider_access_setup.mongodb_atlas_setup_only.aws.atlas_assumed_role_external_id}"
          }
        }
      },
    ]
  })
}

#
# AWS IAM role policy for MongoDB Atlas KMS use
#
resource "aws_iam_role_policy" "mongodb_atlas_setup_policy" {
  name = "mongodb_atlas_setup_policy"
  role = aws_iam_role.mongodb_atlas_setup_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "kms:Encrypt",
          "kms:Decrypt",
          "kms:ReEncrypt*",
          "kms:GenerateDataKey*",
          "kms:DescribeKey"
        ]
        Effect = "Allow"
        Resource = aws_kms_key.aws_kms_key_mongodb_atlas.arn
      },
    ]
  })

  depends_on = [aws_kms_key.aws_kms_key_mongodb_atlas]
}

[...]

resource "mongodbatlas_cloud_provider_access_setup" "mongodb_atlas_setup_only" {
  project_id    = mongodbatlas_project.mongodb_atlas_project.id
  provider_name = "AWS"
}

#
# Perform the authorization for MongoDB Atlas
#
resource "mongodbatlas_cloud_provider_access_authorization" "mongodb_atlas_auth_role" {
  project_id = mongodbatlas_cloud_provider_access_setup.mongodb_atlas_setup_only.project_id
  role_id    = mongodbatlas_cloud_provider_access_setup.mongodb_atlas_setup_only.role_id

  aws {
    iam_assumed_role_arn = aws_iam_role.mongodb_atlas_setup_role.arn
  }
}

#
# Enable encryption at Rest
#
resource "mongodbatlas_encryption_at_rest" "mongodbatlas_encryption_at_rest" {
  project_id = mongodbatlas_project.mongodb_atlas_project.id

  aws_kms_config {
    enabled                = true
    customer_master_key_id = aws_kms_key.aws_kms_key_mongodb_atlas.id
    region                 = var.region
    role_id                = mongodbatlas_cloud_provider_access_authorization.mongodb_atlas_auth_role.role_id
  }
}
```

### Steps to Reproduce

1. Setup Encryption at REST with AWS KMS
2. Rename AWS role resource and so update `iam_assumed_role_arn` in `mongodbatlas_cloud_provider_access_authorization` resource. In my case I renamed from `aws_iam_role.mongodb_atlas_test_role` to `aws_iam_role.mongodb_atlas_setup_role`
3. Expect a crash

### Expected Behavior

AWS Role resource is renamed. We expect an update from mongodbatlas_cloud_provider_access_authorization with new role.

### Actual Behavior

Plugin crashs updating role.

### Debug Output 

```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.mongodb-atlas.aws_iam_role.mongodb_atlas_setup_role has been changed
  ~ resource "aws_iam_role" "mongodb_atlas_setup_role" {
        id                    = "mongodb_atlas_setup_role"
        name                  = "mongodb_atlas_setup_role"
      + tags                  = {}
        # (9 unchanged attributes hidden)

      - inline_policy {}
      + inline_policy {
          + name   = "mongodb_atlas_setup_policy"
          + policy = jsonencode(
                {
                  + Statement = [
                      + {
                          + Action   = [
                              + "kms:Encrypt",
                              + "kms:Decrypt",
                              + "kms:ReEncrypt*",
                              + "kms:GenerateDataKey*",
                              + "kms:DescribeKey",
                            ]
                          + Effect   = "Allow"
                          + Resource = "arn:aws:kms:us-east-1:XXXXXX:key/XXXXXX"
                        },
                    ]
                  + Version   = "2012-10-17"
                }
            )
        }
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.
```

### Crash Output

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.mongodb-atlas.mongodbatlas_cloud_provider_access_authorization.mongodb_atlas_auth_role will be updated in-place
  ~ resource "mongodbatlas_cloud_provider_access_authorization" "mongodb_atlas_auth_role" {
        id              = "aWQ=: XXXXXXXXX-XXXXXXXXX ==: XXXXXXXXX"
        # (4 unchanged attributes hidden)

      ~ aws {
          ~ iam_assumed_role_arn = "arn:aws:iam:: XXXXXXXXX:role/mongo_setup_test_role" -> "arn:aws:iam:: XXXXXXXXX:role/mongodb_atlas_setup_role"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
module.mongodb-atlas.mongodbatlas_cloud_provider_access_authorization.mongodb_atlas_auth_role: Modifying... [id=aWQ=:XXXXXXXXX:YYYYYYYYY]

Stack trace from the terraform-provider-mongodbatlas_v1.0.1 plugin:

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 61 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasCloudProviderAccessAuthorizationUpdate(0x1f45d18, 0xc000049140, 0xc000347d80, 0x1bebf20, 0xc00065abc0, 0xc0008c4320, 0x16cb2ca, 0xc0006d6820)
        github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cloud_provider_access_authorization.go:193 +0xdb9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0005e5dc0, 0x1f45ca8, 0xc00028d680, 0xc000347d80, 0x1bebf20, 0xc00065abc0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:364 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0005e5dc0, 0x1f45ca8, 0xc00028d680, 0xc00013a9a0, 0xc0006d6820, 0x1bebf20, 0xc00065abc0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000a4018, 0x1f45ca8, 0xc00028d680, 0xc0002bf2c0, 0xc00028d680, 0x1cfcb80, 0xc000307100)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000409900, 0x1f45d50, 0xc00028d680, 0xc00013a770, 0xc000409900, 0xc0003071a0, 0xc0006caba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1cfcb80, 0xc000409900, 0x1f45d50, 0xc0003071a0, 0xc00091b380, 0x0, 0x1f45d50, 0xc0003071a0, 0xc00082e400, 0x3cd)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fbc00, 0x1f50b58, 0xc000093380, 0xc0000acc60, 0xc00009f890, 0x250d800, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001fbc00, 0x1f50b58, 0xc000093380, 0xc0000acc60, 0x0)
        google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028e130, 0xc0001fbc00, 0x1f50b58, 0xc000093380, 0xc0000acc60)
        google.golang.org/grpc@v1.38.0/server.go:934 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd

Error: The terraform-provider-mongodbatlas_v1.0.1 plugin crashed!

```

**Comment by themantissa** [comment]
@guyguy333 the team will investigate this report.  Internal ticket INTMDB-256

**Comment by themantissa** [comment]
Fix is completed and will be in our next version, 1.0.2.

**Comment by themantissa** [comment]
We have released the pre-release https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/v1.0.2-pre.1  If anyone here could test and verify before release that would be great.

**Comment by themantissa** [comment]
1.0.2 is out.  Please let us know if any issues remain.
