### ISSUE TITLE
terraform-provider-mongodbatlas_v0.8.0 plugin: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kirusengal** [mongodb/terraform-provider-mongodbatlas#644]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform v1.0.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.5.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.8.0

Your version of Terraform is out of date! The latest version
is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration File 
```hcl
# Create a Project 1
resource "mongodbatlas_project" "atlas-project" {
  org_id = var.atlas_org_id
  name = var.atlas_project_name
}

resource "mongodbatlas_network_container" "test" {
  project_id = mongodbatlas_project.atlas-project.id
  #project_id       = local.project_id
  atlas_cidr_block = "192.168.192.0/18"
  provider_name    = "GCP"
}

# Create the peering connection request
resource "mongodbatlas_network_peering" "test" {
  project_id = mongodbatlas_project.atlas-project.id

  container_id   = mongodbatlas_network_container.test.container_id
  provider_name  = "GCP"

  gcp_project_id = "prjprefix-atlas-play"
  network_name   = "prjprefix-atlas-play"
}

# the following assumes a GCP provider is configured
data "google_compute_network" "the_network" {
  project = "prjprefix-atlas-play"
  name = "prjprefix-atlas-play"
}

# Create the GCP peer
resource "google_compute_network_peering" "peering" {
  name         = "peering-gcp-terraform-test"
  network      = data.google_compute_network.the_network.self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${mongodbatlas_network_peering.test.atlas_gcp_project_id}/global/networks/${mongodbatlas_network_peering.test.atlas_vpc_name}"
  export_subnet_routes_with_public_ip = false
}

resource "mongodbatlas_cluster" "atlas-cluster" {
  project_id = mongodbatlas_project.atlas-project.id
  name         = var.atlas_cluster_name
  cluster_type = "REPLICASET"
  replication_specs {
    num_shards = var.num_shards
    regions_config {
      region_name     = var.atlas_region_name
      electable_nodes = var.num_replicas
      priority        = 7  # Not relevant if single region_config
      read_only_nodes = 0
    }
  }
  auto_scaling_disk_gb_enabled = false
  mongo_db_major_version       = var.mongo_db_major_version

  # Provider Settings "block"
  provider_name               = "GCP"
  disk_size_gb                = var.disk_size_gb
  provider_instance_size_name = var.instance_size_name

  depends_on = [google_compute_network_peering.peering]

}

# Create a Project 2
resource "mongodbatlas_project" "atlas-project2" {
  org_id = var.atlas_org_id
  name = "prjprefix-atlast-play-test2"
}

resource "mongodbatlas_network_container" "test2" {
  project_id = mongodbatlas_project.atlas-project2.id
  #project_id       = local.project_id
  atlas_cidr_block = "192.168.0.0/18"
  provider_name    = "GCP"
}

# Create the peering connection request
resource "mongodbatlas_network_peering" "test2" {
  #project_id       = local.project_id
  #project_id       = var.atlas_project_name
  project_id = mongodbatlas_project.atlas-project2.id

  container_id   = mongodbatlas_network_container.test2.container_id
  provider_name  = "GCP"

  gcp_project_id = "prjprefix-atlas-play"
  network_name   = "prjprefix-atlas-play" # A default VPC in GCP project
}

# Create the GCP peer
resource "google_compute_network_peering" "peering2" {
  name         = "peering-gcp-terraform-test-2"
  network      = data.google_compute_network.the_network.self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${mongodbatlas_network_peering.test2.atlas_gcp_project_id}/global/networks/${mongodbatlas_network_peering.test2.atlas_vpc_name}"
  export_subnet_routes_with_public_ip = false
}

resource "mongodbatlas_cluster" "atlas-cluster2" {
  project_id = mongodbatlas_project.atlas-project2.id
  name         = "prjprefix-atlas-play-test2"
  cluster_type = "REPLICASET"
  replication_specs {
    num_shards = var.num_shards
    regions_config {
      region_name     = var.atlas_region_name
      electable_nodes = var.num_replicas
      priority        = 7  # Not relevant if single region_config
      read_only_nodes = 0
    }
  }
  auto_scaling_disk_gb_enabled = false
  mongo_db_major_version       = var.mongo_db_major_version

  # Provider Settings "block"
  provider_name               = "GCP"
  disk_size_gb                = var.disk_size_gb
  provider_instance_size_name = var.instance_size_name

  depends_on = [google_compute_network_peering.peering2]

}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

### Expected Behavior
Destroy succeeds without error/crash.

### Actual Behavior

Segmentation fault / gaoling panic during destroy

#### Output and stack trace 
```
  Enter a value: yes

mongodbatlas_network_container.test: Destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNWYzNTY0YTc0-cHJvamVjdF9pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl]
mongodbatlas_network_container.test2: Destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZWRhMzQ4ZmE5-cHJvamVjdF9pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 10s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 10s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 20s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 20s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 30s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 30s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 40s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 40s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 50s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 50s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 1m0s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 1m0s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 1m10s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 1m10s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 1m20s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 1m20s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 1m30s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 1m30s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 1m40s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 1m40s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 1m50s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 1m50s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 2m0s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 2m0s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 2m10s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 2m10s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 2m20s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 2m20s elapsed]
mongodbatlas_network_container.test2: Still destroying...
[id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 4m50s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 5m0s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 5m0s elapsed]
mongodbatlas_network_container.test: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFkOTQ0YTgxNW...pZA==:NjFjMTZjN2U2ZmI2NDIxZDllYTFhNTVl, 5m10s elapsed]
mongodbatlas_network_container.test2: Still destroying... [id=Y29udGFpbmVyX2lk:NjFjMTZjODFmZGYxNzA1ZW...pZA==:NjFjMTZjN2UwOTgxODg3YmVkOGU0OTJi, 5m10s elapsed]
╷
│ Error: Request cancelled
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-mongodbatlas_v0.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a7863c]

goroutine 66 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceNetworkContainerRefreshFunc.func1(0xc00054df40, 0xc00054dea0, 0x2, 0x1, 0x1, 0x0)
	github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_network_container.go:304 +0x18c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc00078d080, 0xc0006405b0, 0xc0002e0880, 0xc0002ded80, 0xc0006cb0b0, 0xc0006cb098)
	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/state.go:103 +0x298
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/state.go:80 +0x1bf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a7863c]

goroutine 67 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceNetworkContainerRefreshFunc.func1(0xc000549f40, 0xc000549ea0, 0x2, 0x1, 0x1, 0x0)
	github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_network_container.go:304 +0x18c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1(0xc00078d1a0, 0xc00029a620, 0xc0002e0940, 0xc0002dede0, 0xc0006cb0c0, 0xc0006cb0b8)
	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/state.go:103 +0x298
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
	github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/resource/state.go:80 +0x1bf

Error: The terraform-provider-mongodbatlas_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by themantissa** [comment]
@kirusengal thank you for the report.  The best path forward is to upgrade to the latest provider, 1.1.1, as we've corrected many issues since v0.8.0.
