### ISSUE TITLE
Provider panic with `authentication_enabled=true` input

### ISSUE THREAD

**Issue by jchandler-bhg** [mongodb/terraform-provider-mongodbatlas#873]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
terraform_version = "1.3.2"
mongodbatlas_version = "1.4.6"
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_ldap_configuration" "ldap_configuration_001" {
  project_id             = mongodbatlas_project.project_001.id
  authentication_enabled = true
  authorization_enabled  = true
  hostname               = local.ldap_settings[var.env].hostname
  port                   = 636
  bind_username          = local.ldap_settings[var.env].username
  bind_password          = var.ldap_password
  ca_certificate         = var.ldap_ca_certificate
}
```

### Steps to Reproduce

1. Create an LDAP configuration resource.
2. Run apply for a second time.

### Expected Behavior

Should have updated without a crash.

### Actual Behavior

The provider crashes. This seems to do with the cast in the call to `d.Get` on line 204 [in the ldap_configuration resource](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_ldap_configuration.go#L204).

### Debug Output 

See crash output below.

### Crash Output

```
Stack trace from the terraform-provider-mongodbatlas_v1.4.6 plugin:

panic: interface conversion: interface {} is map[string]interface {}, not bool

goroutine 47 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasLDAPConfigurationUpdate({0xf18288, 0xc0003d67e0}, 0xc000540f00, {0xcbff60?, 0xc000242d90?})
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_ldap_configuration.go:204 +0xa05
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003a0000, {0xf182c0, 0xc00053af90}, 0xd?, {0xcbff60, 0xc000242d90})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003a0000, {0xf182c0, 0xc00053af90}, 0xc000100340, 0xc000540d80, {0xcbff60, 0xc000242d90})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002ac480, {0xf182c0?, 0xc00053ae70?}, 0xc0004762d0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00028e960, {0xf182c0?, 0xc00053a660?}, 0xc0003dc070)
github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd978a0?, 0xc00028e960}, {0xf182c0, 0xc00053a660}, 0xc0003dc000, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000003c0, {0xf1b6a0, 0xc0003bf380}, 0xc000538900, 0xc0003918c0, 0x141a180, 0x0)
google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000003c0, {0xf1b6a0, 0xc0003bf380}, 0xc000538900, 0x0)
google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-mongodbatlas_v1.4.6 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Additional Context

Nothing specifically.

### References

None.

**Comment by evertsd** [comment]
:+1: Thanks for raising this issue, at a first glance the callout of line 204 seems to be spot on. We'll work on getting this issue corrected

**Comment by Zuhairahmed** [comment]
@jchandler-bhg internal ticket is [INTMDB-440](https://jira.mongodb.org/browse/INTMDB-440), will keep you posted when resolved

**Comment by Zuhairahmed** [comment]
@jchandler-bhg as an update, this issue has been picked up in the next sprint cycle and you can expect fix to be included as part of v1.8.1 release next month. will let you know when latest release has been published to the Terraform Registry.

**Comment by Zuhairahmed** [comment]
@jchandler-bhg v1.8.1 has been published to the [Terraform Public Registry](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest)! take a spin and let us know if you need anything else.

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else here
