### ISSUE TITLE
Issue: MongoDB Atlas Plugin Failure v 1.5.0

### ISSUE THREAD

**Issue by mentlak0** [mongodb/terraform-provider-mongodbatlas#928]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/mongodb/mongodbatlas v1.5.0

```

### Terraform Configuration File 

```hcl
terraform {
  backend "remote" {
    organization = "myorg"

    workspaces {
      name = "terraform-mongodb"
    }
  }
  required_version = ">= 1.3.2"
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = ">=1.5.0"
    }
  }
}

provider "mongodbatlas" {
  private_key = var.private
  public_key  = var.public
}
```

### Steps to Reproduce

1. terraform init
2. terraform init -upgrade
3. terraform plan

### Expected Behavior

Full plan of infrastructure to be changed / applied / match

### Actual Behavior

```
│ Error: Plugin did not respond
│ 
│   with mongodbatlas_advanced_cluster.mongodb_adv_cluster,
│   on main.tf line 23, in resource "mongodbatlas_advanced_cluster" "mongodb_adv_cluster":
│   23: resource "mongodbatlas_advanced_cluster" "mongodb_adv_cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

```
Error: The terraform-provider-mongodbatlas_v1.5.0 plugin crashed!

### Crash Output

```
Stack trace from the terraform-provider-mongodbatlas_v1.5.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 62 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.flattenAdvancedReplicationSpecRegionConfigs({0xf1d8e0, 0xc000452840}, {0xc00029c280, 0x2, 0xc000443cb0?}, {0xc000443cd0, 0x1, 0xc000443cb0?}, 0x0?, 0xc00028f000)
        github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_advanced_cluster.go:999 +0x651
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.flattenAdvancedReplicationSpec({0xf1d8e0, 0xc000452840}, 0xc000392280, 0xc0001dced0, 0xa93f8e?, 0xcd4880?)
        github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_advanced_cluster.go:902 +0x1cb
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.flattenAdvancedReplicationSpecs({0xf1d8e0, 0xc000452840}, {0xc00029c260, 0x1, 0xde2f4d?}, {0xc000443ca0, 0x1, 0xf1bf18?}, 0xc00047c398?, 0xc00028f000)
        github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_advanced_cluster.go:940 +0x109
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasAdvancedClusterRead({0xf1d8e0, 0xc000452840}, 0xc00045e400, {0xcc4380?, 0xc00017f730?})
        github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_advanced_cluster.go:480 +0x1b69
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xf1d8e0?, {0xf1d8e0?, 0xc000452840?}, 0xd?, {0xcc4380?, 0xc00017f730?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:719 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00053f960, {0xf1d8e0, 0xc000452840}, 0xc00022eea0, {0xcc4380, 0xc00017f730})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000300018, {0xf1d8e0?, 0xc000452720?}, 0xc0001f2300)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000354000, {0xf1d8e0?, 0xc000452150?}, 0xc000280300)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd9c400?, 0xc000354000}, {0xf1d8e0, 0xc000452150}, 0xc000474620, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ac000, {0xf20d00, 0xc000313380}, 0xc000410120, 0xc000308de0, 0x1422170, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0004ac000, {0xf20d00, 0xc000313380}, 0xc000410120, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-mongodbatlas_v1.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Additional Context

Was working fine some weeks ago since I last checked. I have upgraded the plugin version. Attempted an upgrade which led me to version 1.5.0.

Also tried installing grpc v 1.48.0 - still not working.

Unsure how to fix. Help would be appreciated.

**Comment by evertsd** [comment]
Hi @mentlak0 do you have an example `mongodbatlas_advanced_cluster` terraform config I could use to replicate the issue?

**Comment by mentlak0** [comment]
@evertsd Good Morning, sorry for the delay. 

```
resource "mongodbatlas_advanced_cluster" "mongodb_adv_cluster" {
  project_id                  = var.project_id
  name                        = var.cluster_name
  cluster_type                = var.cluster_type
  backup_enabled              = var.true_bool
  disk_size_gb                = 256
  encryption_at_rest_provider = var.encryption
  mongo_db_major_version      = var.major_version
  pit_enabled                 = var.false_bool
  root_cert_type              = var.root_cert
  advanced_configuration {
    fail_index_key_too_long              = var.false_bool
    javascript_enabled                   = var.true_bool
    minimum_enabled_tls_protocol         = "TLS1_2"
    no_table_scan                        = var.false_bool
    oplog_size_mb                        = 13108
    sample_refresh_interval_bi_connector = 3600
  }
  replication_specs {
    zone_name = "Zone 1"
    region_configs {
      electable_specs {
        instance_size = var.provider_tier
        node_count    = 3
      }
      #read only nodes that can be available to enable local reads
      read_only_specs {
        instance_size = var.provider_tier
        disk_iops = 0
        node_count = 0
      }
      priority      = 7
      provider_name = var.provider_name
      region_name   = var.region_name

      auto_scaling {
        compute_enabled            = var.true_bool
        compute_max_instance_size  = "M60"
        compute_min_instance_size  = "M30"
        compute_scale_down_enabled = var.true_bool
        disk_gb_enabled            = var.false_bool
      }
    }
  }
}
```

**Comment by mentlak0** [comment]
@evertsd  Hello, hope you're well. 

Any updates with this? 

I tried to downgrade to previous version I was using when was working. v1.4.1 and still getting same errors.

Be good to have a reply soon.

**Comment by evertsd** [comment]
@mentlak0 based on the crash log it seems like this may be due to a mismatch in the replication_specs/region_configs. I'm curious, does your live cluster only have one replication spec & region config?

A way to confirm this would be to import the cluster into a separate workspace and examine the resulting `terraform.tfstate`
```
terraform import mongodbatlas_advanced_cluster.mongodb_adv_cluster ${PROJECT_ID}-${CLUSTER_NAME}
```

**Comment by evertsd** [comment]
@mentlak0 hoping you were able to resolve the issue, but for what it's worth I think this may also be a bug in the provider. Namely the provider should've recognized a diff in that configuration properly and attempted to apply those changes.
